# Generated by Django 6.0.3 on 2026-03-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers/')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('competences', models.TextField(blank=True, help_text='Ex: informatique, médecine, agriculture', verbose_name='Compétences')),
                ('langues', models.CharField(blank=True, help_text='Ex: Français, Anglais, Ewe', max_length=200)),
                ('disponibilite', models.CharField(choices=[('weekend', 'Weekends'), ('semaine', 'En semaine'), ('temps_plein', 'Temps plein'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénévole',
                'verbose_name_plural': 'Bénévoles',
                'ordering': ['-created_at'],
            },
        ),
    ]
