# Generated by Django 6.0.3 on 2026-03-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/')),
                ('type_org', models.CharField(choices=[('ong', 'ONG'), ('association', 'Association'), ('fondation', 'Fondation'), ('gouvernement', 'Gouvernement'), ('ecole', 'École'), ('hopital', 'Hôpital')], default='association', max_length=20)),
                ('description', models.TextField()),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['-created_at'],
            },
        ),
    ]
