# Generated by Django 6.0.3 on 2026-03-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('domaine', models.CharField(choices=[('education', 'Éducation'), ('sante', 'Santé'), ('environnement', 'Environnement'), ('tech', 'Technologie'), ('agriculture', 'Agriculture'), ('droits', 'Droits humains'), ('sport', 'Sport'), ('culture', 'Culture & Arts'), ('autre', 'Autre')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='missions/')),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('places_disponibles', models.PositiveIntegerField(default=1)),
                ('duree', models.CharField(choices=[('1_semaine', '1 semaine'), ('2_semaines', '2 semaines'), ('1_mois', '1 mois'), ('3_mois', '3 mois'), ('6_mois', '6 mois'), ('1_an', '1 an ou plus')], max_length=20)),
                ('competences_requises', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='ouverte', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Lettre de motivation')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='volunteers.volunteer')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-created_at'],
                'unique_together': {('mission', 'volunteer')},
            },
        ),
    ]
